### ISSUE TITLE
Continuous Integration policy?

### ISSUE THREAD

**Issue by richelbilderbeek** [viewizard/astromenace#37]
## Expected Behavior

I expect high-quality code repositories to do Continuous Integration tests, such as by GitHub Actions. The results of these builds can be seen in an 'Actions' tab (next to the 'Code' , 'Issues', 'Pull requests', etc. tabs)

## Actual Behavior

The tab 'Actions' is removed. There is no CI at all.

## Steps to Reproduce the Problem

  1. Go to https://github.com/viewizard/astromenace 
  2. Search for the tab 'Actions': it is not there

## Misc

I do volunteer to add and maintain this. I would enjoy to see one of my favorite games to show its high quality code :-)

**Comment by viewizard** [comment]
Previously, astromenace had CI/CD (travis-ci org), disabled now. I don't really see any reason use now CI/CD for suspended project like astromenace with release/changes one per 5 years and with code changes from only one persone (me, heh) or for community (looks like only from linux distro maintainers) PRs that require some investigation instead of test build all around in CI (like new gcc version changes, some particular linux distro env changes, etc. ...).

**Comment by richelbilderbeek** [comment]
Clear answer, thanks!

Thanks for Astromenace, it is an awesome game!
