### ISSUE TITLE
Support for language PT-BR

### ISSUE THREAD

**Issue by LeandroStanger** [viewizard/astromenace#6]

**Comment by viewizard** [comment]
Added to the list at Crowdin
https://crowdin.com/project/astromenace

**Comment by viewizard** [comment]
Leandro, thank you for your work!

Unfortunately, I noticed, that you translation have issues:
1) please, make sure, that your translation use all capital letters if initial text have all capital letters. Some text are used for buttons titles, so, all languages should looks in the same way.
2) please, make sure, that your translation don't use first capital letter if initial text don't have it. We have a reason for this, since some text could be concatenated with another, first capital letter could looks wrong in the middle of the text.
3) please, don't change paths to files and use initial paths 'as is', if you don't plan to submit artwork and voice. At this moment I don't have resources to hire someone to make this work (and we don't have volunteers).
